In [19]:
fruits = ["mango","apple","banana"]

Numbers = [12, 13, 14, 17, 18]

score = [2,3,4,5,6]

In [5]:
Numbers + score

[12, 13, 14, 17, 18, 2, 3, 4, 5, 6]

In [6]:
sum(Numbers)

74

In [7]:
sum(score)

20

In [8]:
sum(Numbers) + sum(score)

94

In [12]:
#complex operations cannot be performed on a list e.g multiplication, mean, std, median etc

Numbers*score

TypeError: can't multiply sequence by non-int of type 'list'

 the difference between list and array is that we can perdform complex mathematical opperations on an array
 array is a function that is used to convert a sequence to an array
 
 array must have desame number of values.
 numpy is called numericalpython and used to perform numerical opertaions.

In [21]:
#convert the list to an array
import numpy as pd

numpy.array(Numbers)

array([12, 13, 14, 17, 18])

In [25]:
numpy.array(Numbers)* numpy.array(score)

array([ 24,  39,  56,  85, 108])

In [17]:
#variable = value

c= numpy.array(Numbers)
d= numpy.array(score)

c*d

array([ 24,  39,  56,  85, 108])

In [31]:
fruitsville = [1,2,3,20,100]

In [32]:
numpy.array(fruitsville)

array([  1,   2,   3,  20, 100])

In [33]:
fruitsville1 = ["gabbs","koka","dbs","konwea","specialist"]

In [35]:
numpy.array(fruitsville1)

array(['gabbs', 'koka', 'dbs', 'konwea', 'specialist'], dtype='<U10')

# markdown

In [ ]:
# to check the number of dimension we use ndim (to check the amount of arrays)

In [36]:
c.ndim

1

In [37]:
c

array([12, 13, 14, 17, 18])

In [40]:
counts = numpy.array([[1,2,3,4],[5,6,7,8]])

In [42]:
print(counts)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
#1. create a list that contains the month of the yearthen convert the list to an array
#2 create a user defined functioin that returns the month of the year

In [9]:
month=["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"]


In [11]:
import numpy
numpy.array(month)

array(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep',
       'oct', 'nov', 'dec'], dtype='<U3')

In [12]:
y=numpy.array(month)

In [21]:
def y():
    return month
y()

['jan',
 'feb',
 'mar',
 'apr',
 'may',
 'jun',
 'jul',
 'aug',
 'sep',
 'oct',
 'nov',
 'dec']